<?xml version="1.0" ?>
<definitions name="soap" targetNamespace="urn:soap" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:soap" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types xmlns="http://schemas.xmlsoap.org/wsdl/" />
<portType name="soapPort"><operation name="create">
<input message="tns:createRequest" />
<output message="tns:createResponse" />
</operation>
</portType>
<binding name="soapBinding" type="tns:soapPort">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
<operation name="create">
<soap:operation soapAction="urn:soap#VodWebservice#create" />
<input><soap:body use="encoded" namespace="urn:soap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</input>
<output>
<soap:body use="encoded" namespace="urn:soap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</output>
</operation>
</binding>
<service name="soap">
<documentation />
<port name="soapPort" binding="tns:soapBinding"><soap:address location="http://localhost/livsns/api/webservice/sobey/VodWebservice.php" />
</port>
</service>
<message name="createRequest">
<part name="xml" type="xsd:string" />
</message>
<message name="createResponse">
<part name="create" type="xsd:string" />
</message>
</definitions>