<?php
$errorConf = array(
	NOID                 =>'未传入查询ID',
	EXISTS_TUJI          =>'此分类存在图集，无法删除',
	NODATA               =>'无更新数据',
	NOMETHOD             =>'方法不存在',
	EXISTS               =>'分类名称已经存在',
	JS_FILE_EXISTS       =>'文件已经存在',
	TYPE_ERROR           =>'文件类型错误',
	IS_BLACK_MEMBER      =>'您暂时没有权限发表评论！',
    NO_POSTS             =>'帖子不存在',
    THIS_SORT_NOT_EXISTS =>'该分类不存在',
	NO_SECTION_NAME => '版块名称不能为空',
	NO_SORT_ID      => '社区id为空',
	CREATE_FAIL     => '创建失败',
	PARAM_WRONG     => '参数错误',
	UPDATE_FAIL     => '更新失败',
	DELETE_FAIL     => '删除失败',
	NO_APPID        => 'APPID为空',
	NO_COMMENT_TYPE => '没有选择评论类型',	
	NO_SECTION_ID   => '没有版块id',
	NO_SECTION      => '该版块已被主人删除或不存在',
	HAS_JOINT       => '您已经赞过此内容',
	NO_MEMBER_INFO	=> '会员信息不存在',
	UPLOAD_IMG_FAIL => '图片上传失败',
	DELETE_JOINT_FAIL => '取消赞失败',	
	SEEKHELP_IS_BLACK => '社区已被列为黑名单，请联系管理员',
	NO_MEMBER_ID => '没有会员ID'	,
	NO_JOINT_TYPE=> '赞类型为空',	
	NO_CONTENT	=> '请输入内容',
    NO_SORT_NAME  => '社区名称不能为空',
    SECTION_HAS_MAX => '已达到版块最大数量',
    NO_TYPE => '未提交类型',
    POSTING_FAST => '发帖频率过快，请稍后再试',
    CONTENT_EXIST => '请勿重复发表同样内容',
	NO_COMMENT_INFO => '评论不存在',

) ;