<?php
/***************************************************************************
* LivSNS 0.1
* (C)2004-2010 HOGE Software.
*
* $Id: error.conf.php 5351 2011-12-15 08:54:57Z zhuld $
***************************************************************************/

$errorConf = array(
	UNKNOW 					=> '未知错误',
	OBJECT_NULL 			=> '对象为空',
	SUCCESS 				=> '成功',
	FAILED 					=> '失败',
	NO_APPID 				=> '应用id不存在',
	PARAM_WRONG 			=> '参数错误',
	NAME_EXISTS 			=> '中文名重复',
	ENGLISH_EXISTS 			=> '英文名重复',
	TYPE_ERROR 				=> '类型错误',
	TYPE_ERROR1 			=> '引导图类型错误',
	TYPE_ERROR2 			=> '应用图标类型错误',
	TYPE_ERROR3 			=> '启动画面类型错误',
	TYPE_ERROR4 			=> '导航栏标题类型错误',
	TYPE_ERROR5 			=> '首页背景类型错误',
	SIZE_ERROR 				=> '尺寸错误',
	SIZE_ERROR1 			=> '引导图尺寸错误',
	SIZE_ERROR2 			=> '应用图标尺寸错误',
	SIZE_ERROR3 			=> '启动画面尺寸错误',
	SIZE_ERROR4 			=> '导航栏标题尺寸错误',
	SIZE_ERROR5 			=> '首页背景尺寸错误',
	OVER_LIMIT 				=> '超过限制个数',
	URL_NOT_VALID 			=> 'URL地址无效',
	CHAR_OVER 				=> '超过限定字符长度',
	COLOR_ERROR 			=> '颜色值错误',
	FILE_TYPE_ERROR 		=> '模块上传图标压缩包类型有误',
	APP_ICON_ERROR 			=> 'APP图标未上传或上传有误',
	APP_STARTPIC_ERROR 		=> 'APP启动画面未上传或上传有误',
	MARK_EXISTS 			=> '标识重复',
	NAME_REPEAT 			=> '名称重复',
	NO_SOLIDIFY_ID 			=> '没有固化模块id',
	NO_USER_ID 				=> '没有用户id',
	NO_SOLIDIFY_PARAM 		=> '没有固化参数',
	NO_CONFIG_ID 			=> '没有配置id',
	PROPERTY_AUTH_FAIL 		=> '属性验证失败',
	COLUMN_SORT_WRONG 		=> '栏目排序错误',
	NOID 					=> '没有id',
	APP_ID_EXISTS_ERROR 	=> '所传应用id有误',
	CLIENT_INFO_NOT_EXISTS 	=> '客户端信息不存在',
	APP_NOT_EXISTS 			=> '该应用不存在',
	NO_CLIENT_TYPE 			=> '没有客户端类型',
	NO_APP_ID 				=> '没有应用id',
	CUR_VERSION_TOO_LOW 	=> '当前版本小于上一个版本',
	NO_VERSION_INFO 		=> '没有版本信息',
	NO_APP_ID_OR_CLIENT_TYPE=> '没有应用id或者没有客户端类型',
	NO_VERSION_ID			=> '没有版本id',
	NO_QUEUE_ID				=> '没有队列id',
	NO_VERSION_ID_OR_QUEUE_ID	=> '没有版本id或者队列id',
	NO_VERSION_NUM			=> '没有版本号',
	VERSION_NUM_ERROR		=> '版本号有错',
	ERR_SHARE_DATA			=> '分享数据有误',
	NO_UUID					=> '没有uuid',
	NO_SYSTEM_ICON_URL		=> '系统图标下载地址不能为空',
	NO_NAME					=> '没有用户名',
	NO_DINGDONE_NAME		=> '没有叮当用户名',
	NO_DINGDONE_USER_ID		=> '没有叮当用户id',
	NO_TYPE					=> '没有申请类型',
	NO_IDENTITY_TYPE		=> '没有身份类型',
	NO_ID_OR_QUEUE_ID		=> '没有版本id或者queue_id',
	NO_TPL_NAME				=> '没有模板名称',
	NO_TPL_HTML				=> '没有正文HTML',
	NO_LOGIN				=> '未登陆',
	NO_STATUS				=> '没有状态',
	NO_PROVINCE_CODE		=> '没有省的地区码',
	NO_ACCOUNT_NAME			=> '没有账号名',
	NO_PASSWORD				=> '没有密码',
	NO_PLANT_TYPE			=> '没有平台类型',
	NO_CITY_CODE			=> '没有城市的地区码',
	THIS_USER_NOT_PUSH_API	=> '该用户还未配置推送接口',
	MSG_CAN_NOT_EMPTY		=> '推送的消息不能为空',
	NO_MODULE_ID			=> '没有模块id',
	NO_CONTENT_ID			=> '没有内容id',
	NO_MODULE_MARK			=> '没有模块标识',
	NO_PUSH_URL				=> '没有推送链接',
	NO_SELECT_OPEN_MODE		=> '没有选择打开模式',
	NO_SELECT_DEVICE_TYPE	=> '未选择终端类型',
	DEVICE_TYPE_ERR			=> '终端类型有误',
	IDENTITY_AUTH_HAS_EXISTS=> '您的申请已存在',
	MSG_IS_TOO_LONG			=> '消息过长',
	GUIDE_PIC_ERROR         => '引导图上传错误'
);
?>