<?php 
$errorConf = array(
    UNKNOW 	        => '未知错误',
    NO_APPID        => '没有应用id',
    UPDATE_APP_FAIL => '记录信息失败',
    NO_USERID       => '用户id为空',
    NO_RC_INFO      => '此应用未绑定聊天服务',
    NO_GROUP_ID     => '未提交群组id',
   // NO_ACCESS_TOKEN => '会话已过期，请重新登录',
    IS_JOIN         => '此用户已经在该群组里',
    NO_SESSION_ID   => '群组id是空值',
    UPDATE_ERROR    => '更新失败',
    NUMBERS_FULL    => '此群人数已满',
    REQUEST_FAIL    => '请求失败',
    PARAM_WRONG     => '参数错误',
    IM_IS_BLACK     => '群组已被列为黑名单，请联系管理员',
    NO_USER_AVATAR  => '没有群组用户头像',
    HAS_MAX_GROUP   => '已达到群组最大数量',
    NO_GROUP_INFO   => '群组信息不存在',
    CREATE_GROUP_USER_FAIL => '创建群组成员失败',
    HAS_CREATE      => '记录已存在',
    NO_MEMBER_ID    => '未提交会员ID',
    NO_MEMBER_INFO  => '会员不存在',
    NO_GROUP_USER   => '群组成员不存在',
    NO_APP_ID       => '未提交应用ID',
    REQUEST_IM_FAIL => '请求聊天服务出错',
);