ps
df
top
sar
ls
ln
chmod
ping
/etc/init.d/WowzaMediaServer
/usr/local/TranscodeServer/build/start.sh
/usr/local/TranscodeServer/build/stop.sh
/usr/local/HogeTrans/build/start.sh
/usr/local/HogeTrans/build/stop.sh
/usr/local/nginx/sbin/nginx
/etc/init.d/php-fpm
/usr/local/php/sbin/php-fpm
/usr/local/php-cgi/sbin/php-fpm
/etc/init.d/mysql
/etc/init.d/mysqld
/etc/init.d/varnishd
/etc/init.d/httpd