<?php $data = array (
  'id' => '341',
  'title' => '测试问卷',
  'brief' => '就业',
  'problem_num' => '5',
  'submit_num' => '0',
  'column_id' => '3',
  'indexpic' => NULL,
  'status' => '0',
  'node_id' => '5',
  'used_survey_id' => '0',
  'start_time' => '2014-04-01 11:03:00',
  'end_time' => 0,
  'is_time' => '1',
  'question_time' => '14400',
  'picture_ids' => '113',
  'video_ids' => '29201',
  'audio_ids' => '29202',
  'publicontent_ids' => '354031',
  'is_ip' => '0',
  'ip_limit_time' => '0',
  'is_login' => '0',
  'is_auto_submit' => '0',
  'is_result_public' => '0',
  'is_verifycode' => '0',
  'verify_type' => '0',
  'order_id' => '341',
  'user_id' => '454',
  'update_user_id' => '0',
  'audit_user_id' => '0',
  'user_name' => 'janice',
  'update_user_name' => '',
  'audit_user_name' => '',
  'org_id' => '4',
  'appid' => '0',
  'appname' => 'MCP网页版',
  'create_time' => '2014-04-17 10:58:08',
  'update_time' => '2014-04-17 10:58:08',
  'audit_time' => 0,
  'ip' => '10.0.2.44',
  'expand_id' => '0',
  'column_url' => '',
  'pub_time' => '0',
  'sort_name' => '就业情况',
  'column_name' => '新闻',
  'use_hour' => 4,
  'use_minute' => 0,
  'use_second' => 0,
  'pictures' => 
  array (
    0 => 
    array (
      'id' => '113',
      'img_info' => 'http://img.dev.hogesoft.com:233/material/survey/img/2014/04/20140417110157vyXD.jpg',
      'upload_type' => '图片',
      'img_arr' => 
      array (
        'host' => 'http://img.dev.hogesoft.com:233/',
        'dir' => 'material/survey/img/',
        'filepath' => '2014/04/',
        'filename' => '20140417110157vyXD.jpg',
      ),
    ),
  ),
  'videos' => 
  array (
    0 => 
    array (
      'id' => '29201',
      'img_info' => 'http://img.dev.hogesoft.com:233/material/mediaserver/img/2014/04/9f2e7711994ba2ae81f16b74db7aa024.jpg',
      'is_audio' => '0',
      'upload_type' => '视频',
      'title' => '测试小视频',
      'play_url' => 'http://vfile1.dev.hogesoft.com:233/2014/1397/7037/8675/139770378675.ssm/manifest.f4m',
      'm3u8' => 'http://vfile1.dev.hogesoft.com:233/2014/1397/7037/8675/139770378675.ssm/139770378675.m3u8',
      'video_arr' => 
      array (
        'hostwork' => 'http://vfile1.dev.hogesoft.com:233',
        'video_base_path' => '/web/mediauploads/mp4/',
        'video_path' => '2014/1397/7037/8675/139770378675.ssm/',
        'video_filename' => '139770378675.mp4',
      ),
    ),
  ),
  'audios' => 
  array (
    0 => 
    array (
      'id' => '29202',
      'img_info' => '',
      'is_audio' => '0',
      'upload_type' => '视频',
      'title' => '爸爸去哪儿',
      'play_url' => 'http://vfile1.dev.hogesoft.com:233/2014/1397/7037/9861/139770379861.ssm/manifest.f4m',
      'm3u8' => 'http://vfile1.dev.hogesoft.com:233/2014/1397/7037/9861/139770379861.ssm/139770379861.m3u8',
      'video_arr' => 
      array (
        'hostwork' => 'http://vfile1.dev.hogesoft.com:233',
        'video_base_path' => '/web/mediauploads/mp4/',
        'video_path' => '2014/1397/7037/9861/139770379861.ssm/',
        'video_filename' => '139770379861.mp4',
      ),
    ),
  ),
  'publicontents' => 
  array (
    0 => 
    array (
      'id' => '354031',
      'title' => '28日魅力乡村',
      'brief' => '',
      'bundle_id' => 'livmedia',
      'module_id' => 'vod',
      'content_url' => 'http://www.hoge.cn/folder3/folder1223/2011-03-03/354031.html',
      'content_fromid' => '29172',
      'img_info' => 'http://img.dev.hogesoft.com:233/material/mediaserver/img/2014/04/51b41d35b18e91d30f692bf89e0e1f1f.jpg',
      'img_arr' => 
      array (
        'host' => 'http://img.dev.hogesoft.com:233/',
        'dir' => 'material/mediaserver/img/',
        'filepath' => '2014/04/',
        'filename' => '51b41d35b18e91d30f692bf89e0e1f1f.jpg',
      ),
      'upload_type' => '引用',
      'module_name' => '媒体库',
    ),
  ),
  'problems' => 
  array (
    0 => 
    array (
      'id' => '3668',
      'survey_id' => '341',
      'title' => '姓名|性别|年龄|学历',
      'picture' => NULL,
      'description' => '',
      'type' => '3',
      'is_required' => '1',
      'is_other' => '0',
      'min_option' => '0',
      'max_option' => '0',
      'tips' => '',
      'counts' => '0',
      'order_id' => '0',
      'type_name' => '填空题',
      'options' => 
      array (
        0 => 
        array (
          'id' => '156251',
          'survey_id' => '341',
          'problem_id' => '3668',
          'name' => '姓名',
          'is_other' => '0',
          'type' => '3',
          'char_num' => '4',
          'total' => '0',
          'order_id' => '156251',
        ),
        1 => 
        array (
          'id' => '156252',
          'survey_id' => '341',
          'problem_id' => '3668',
          'name' => '性别',
          'is_other' => '0',
          'type' => '3',
          'char_num' => '2',
          'total' => '0',
          'order_id' => '156252',
        ),
        2 => 
        array (
          'id' => '156253',
          'survey_id' => '341',
          'problem_id' => '3668',
          'name' => '年龄',
          'is_other' => '0',
          'type' => '3',
          'char_num' => '3',
          'total' => '0',
          'order_id' => '156253',
        ),
        3 => 
        array (
          'id' => '156254',
          'survey_id' => '341',
          'problem_id' => '3668',
          'name' => '学历',
          'is_other' => '0',
          'type' => '3',
          'char_num' => '10',
          'total' => '0',
          'order_id' => '156254',
        ),
      ),
    ),
    1 => 
    array (
      'id' => '3669',
      'survey_id' => '341',
      'title' => '就业时，最想进入的行业（）',
      'picture' => NULL,
      'description' => '',
      'type' => '1',
      'is_required' => '1',
      'is_other' => '0',
      'min_option' => '1',
      'max_option' => '1',
      'tips' => '',
      'counts' => '0',
      'order_id' => '1',
      'type_name' => '单选题',
      'options' => 
      array (
        0 => 
        array (
          'id' => '156255',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => '金融、保险、证券',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156255',
        ),
        1 => 
        array (
          'id' => '156256',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => '商贸业',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156256',
        ),
        2 => 
        array (
          'id' => '156257',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => '房地产业',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156257',
        ),
        3 => 
        array (
          'id' => '156258',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => 'IT与通讯',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156258',
        ),
        4 => 
        array (
          'id' => '156259',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => '医药食品业',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156259',
        ),
        5 => 
        array (
          'id' => '156260',
          'survey_id' => '341',
          'problem_id' => '3669',
          'name' => '政府机关',
          'is_other' => '0',
          'type' => '1',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156260',
        ),
      ),
    ),
    2 => 
    array (
      'id' => '3670',
      'survey_id' => '341',
      'title' => '你选择这个行业的主要原因是基于（）',
      'picture' => NULL,
      'description' => '',
      'type' => '2',
      'is_required' => '1',
      'is_other' => '1',
      'min_option' => '1',
      'max_option' => '4',
      'tips' => '',
      'counts' => '0',
      'order_id' => '2',
      'type_name' => '多选题',
      'options' => 
      array (
        0 => 
        array (
          'id' => '156261',
          'survey_id' => '341',
          'problem_id' => '3670',
          'name' => '属于朝阳行业，发展空间大',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156261',
        ),
        1 => 
        array (
          'id' => '156262',
          'survey_id' => '341',
          'problem_id' => '3670',
          'name' => '该行业收入较高',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156262',
        ),
        2 => 
        array (
          'id' => '156263',
          'survey_id' => '341',
          'problem_id' => '3670',
          'name' => '与自己专业对口',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156263',
        ),
        3 => 
        array (
          'id' => '156264',
          'survey_id' => '341',
          'problem_id' => '3670',
          'name' => '稳定',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156264',
        ),
      ),
    ),
    3 => 
    array (
      'id' => '3671',
      'survey_id' => '341',
      'title' => '你最想通过哪种渠道获得招聘信息（）',
      'picture' => NULL,
      'description' => '',
      'type' => '2',
      'is_required' => '1',
      'is_other' => '1',
      'min_option' => '1',
      'max_option' => '4',
      'tips' => '',
      'counts' => '0',
      'order_id' => '3',
      'type_name' => '多选题',
      'options' => 
      array (
        0 => 
        array (
          'id' => '156265',
          'survey_id' => '341',
          'problem_id' => '3671',
          'name' => '学校就业指导中心',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156265',
        ),
        1 => 
        array (
          'id' => '156266',
          'survey_id' => '341',
          'problem_id' => '3671',
          'name' => '招聘网站',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156266',
        ),
        2 => 
        array (
          'id' => '156267',
          'survey_id' => '341',
          'problem_id' => '3671',
          'name' => '招聘会',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156267',
        ),
        3 => 
        array (
          'id' => '156268',
          'survey_id' => '341',
          'problem_id' => '3671',
          'name' => '专业媒体',
          'is_other' => '0',
          'type' => '2',
          'char_num' => '0',
          'total' => '0',
          'order_id' => '156268',
        ),
      ),
    ),
    4 => 
    array (
      'id' => '3672',
      'survey_id' => '341',
      'title' => '你认为当前毕业生就业主要问题是什么？',
      'picture' => NULL,
      'description' => '',
      'type' => '4',
      'is_required' => '1',
      'is_other' => '0',
      'min_option' => '1',
      'max_option' => '10',
      'tips' => '',
      'counts' => '0',
      'order_id' => '4',
      'type_name' => '问答题',
      'options' => NULL,
    ),
  ),
); ?>