<?php
	$errorConf = array(
		NOFILE 					=> '没有文件传输',
		FORBIDTYPE 				=> '非法视频类型',
		NOWRITE 				=> '目录不可写',
		FAILMOV 				=> '视频文件',
		NOID 					=> '没有视频id',
		NOFUC 					=> '没有此方法',
		NOMARKTYPE 				=> '没有标注类型',
		NOMATCH 				=> '视频信息不匹配',
		FAILMOVE 				=> '移动失败',
		TIMEERROR 				=> '结束时间设置错误',
		NOTFINDVIDEO 			=> '未找到视频信息',
		NODATA 					=> '没有数据',
		NOURL 					=> '没有url',
		NOTCONNECT				=> '连接不上服务器',
		NO_SELECT_TRANSERVER 	=> '未选择转码服务器',
		NOTFINDFILE 			=> '找不到视频文件',
		FAILMOREBIT				=> '多码流失败',
		EXECAFTERMOREBIT		=> '当前有转码任务请稍后执行多码流',
		NOVIDEOS				=> '没有可用的视频',
		NOMOREBITRATE			=> '没有多条码流配置',
		NO_VIDEO_IS_TRANSCODING	=> '没有视频正在转码',
		NO_TRANSERVER_CAN_USE	=> '没有可用的转码服务器',
		NO_VIDEO_LEAVE_OUT		=> '没有遗漏转码的视频',
		NO_VIDEO_IS_FAILED		=> '没有失败的视频',
		NO_FAILED_VIDEOS_FROM_MORE	=> '没有多码流失败的视频',
		EXECAFTERTRANSCODE		=> '当前有转码任务请稍后操作',
		DIR_ERROR				=> '输入的目录有误',
		NO_VIDEO_IN_DIR			=> '该目录内没有可用的视频',
		FTP_UPLOAD_DIR_EMPTY	=> '大视频转码目录设置错误，请前往应用设置修改“大视频转码目录”配置，同时确保该目录存在可读可写，然后将视频通过其他方式上传至该目录，上述成功之后便可以通过此功能对大视频转码，减少上传时间',
		DISC_SPACE_NOT_ENOUGH	=> '空间不足',
		DIR_NOT_EXISTS_OR_NOT_WRITEABLE	=> '目录不存在或者不可写',
		NO_SERVER_ID	=> '没有转码服务器id',
		NOT_FIND_SOURCE_VIDEO_FILE => '找不到源视频文件',
	);
?>