<?php $data = array (
  'id' => '189',
  'title' => 'lulutest',
  'brief' => '',
  'node_id' => '4',
  'status' => '0',
  'counts' => '69',
  'is_login' => '0',
  'is_verifycode' => '0',
  'verifycode_type' => '0',
  'order_id' => '188',
  'org_id' => '4',
  'user_id' => '221',
  'user_name' => 'lulu',
  'create_time' => '2014-04-09 13:52:40',
  'update_user_id' => '368',
  'update_user_name' => 'Qiang',
  'update_time' => '2014-04-15 16:22:44',
  'audit_user_id' => '0',
  'audit_user_name' => '',
  'audit_time' => 0,
  'ip' => '10.0.2.92',
  'appid' => '55',
  'appname' => 'MCP网页版',
  'expand_id' => '0',
  'pub_time' => '0',
  'sort_name' => '意见或建议',
  'forms' => 
  array (
    0 => 
    array (
      'id' => '459',
      'name' => '姓名',
      'fid' => '189',
      'brief' => '',
      'fixed_id' => '1',
      'is_required' => '1',
      'is_name' => '1',
      'order_id' => '0',
      'is_common' => 0,
      'form_type' => 1,
      'standard_type' => 1,
      'width' => '450',
      'height' => '30',
      'char_num' => 20,
      'type' => 'fixed',
    ),
    1 => 
    array (
      'id' => '458',
      'name' => '地址',
      'fid' => '189',
      'brief' => '',
      'fixed_id' => '4',
      'is_required' => '1',
      'conf' => '11',
      'is_name' => '0',
      'order_id' => '1',
      'is_common' => 0,
      'form_type' => 4,
      'element' => 
      array (
        0 => 
        array (
          'name' => '请填写详细地址',
          'form_type' => 1,
          'fixed_id' => 4,
          'id' => '11',
        ),
      ),
      'type' => 'fixed',
    ),
    2 => 
    array (
      'id' => '456',
      'name' => '日期',
      'fid' => '189',
      'brief' => '',
      'fixed_id' => '5',
      'is_required' => '1',
      'is_name' => '0',
      'order_id' => '2',
      'is_common' => 0,
      'form_type' => 5,
      'standard_type' => 1,
      'width' => 450,
      'height' => 30,
      'char_num' => 30,
      'start_time' => '2010',
      'end_time' => '2014',
      'type' => 'fixed',
    ),
    3 => 
    array (
      'id' => '916',
      'name' => '上传附件',
      'brief' => '',
      'fid' => '189',
      'form_type' => 5,
      'width' => '0',
      'height' => '0',
      'char_num' => '0',
      'is_required' => '0',
      'options' => '',
      'cor' => '0',
      'limit_type' => '0',
      'op_num' => '0',
      'spilter' => '0',
      'is_name' => '0',
      'order_id' => '3',
      'is_common' => 0,
      'type' => 'standard',
    ),
    4 => 
    array (
      'id' => '913',
      'name' => '下拉选择',
      'brief' => '',
      'fid' => '189',
      'form_type' => 4,
      'width' => '0',
      'height' => '0',
      'char_num' => '0',
      'is_required' => '0',
      'options' => 
      array (
        0 => '选项一',
        1 => '选项二',
      ),
      'cor' => '0',
      'limit_type' => '2',
      'op_num' => '1',
      'spilter' => '0',
      'is_name' => '0',
      'order_id' => '4',
      'is_common' => 0,
      'type' => 'standard',
    ),
    5 => 
    array (
      'id' => '912',
      'name' => '单选/多选',
      'brief' => '',
      'fid' => '189',
      'form_type' => 3,
      'width' => '0',
      'height' => '0',
      'char_num' => '0',
      'is_required' => '1',
      'options' => 
      array (
        0 => '选项一',
        1 => '选项三',
        2 => '4',
      ),
      'cor' => '2',
      'limit_type' => '1',
      'op_num' => '3',
      'spilter' => '0',
      'is_name' => '0',
      'order_id' => '5',
      'is_common' => 0,
      'type' => 'standard',
    ),
    6 => 
    array (
      'id' => '842',
      'name' => '电话',
      'brief' => '',
      'fid' => '189',
      'form_type' => 1,
      'width' => '150',
      'height' => '30',
      'char_num' => '2',
      'is_required' => '0',
      'options' => '',
      'cor' => '0',
      'limit_type' => '0',
      'op_num' => '0',
      'spilter' => '0',
      'is_name' => '1',
      'order_id' => '6',
      'is_common' => 0,
      'type' => 'standard',
    ),
  ),
); ?>